/* =========================================================
   PRCOME — PR회사 공용 데이터 (agencies.html 목록 + company.html 상세 공유)
   출처: 한국PR협회 PR회사 (koreapr.org) 기준 참고용 정리
   각 항목: [회사명, 대표, 공식 홈페이지]
   ========================================================= */
window.PR_COMPANIES=[
 ['굿미디어','윤연희','http://www.goodmedia21.com/'],
 ['굿윌커뮤니케이션즈㈜','박용집','http://www.goodwillpr.co.kr'],
 ['㈜그레이프피알앤컨설팅','최승기','http://www.grapepr.com/'],
 ['㈜너츠커뮤니케이션','한상진','http://www.nutscomm.co.kr/'],
 ['뉴스피알','박중오','http://www.potalnews.co.kr/gnuboard4/'],
 ['더니즈앤씨즈커뮤니케이션랩','명성옥','https://theneedsnseeds.com/'],
 ['더스프링컴퍼니','최승주','http://www.thespring.co.kr/'],
 ['더피알','김진희','http://www.t-pr.co.kr/'],
 ['도모㈜','이선종','http://domo.co.kr/'],
 ['대한미디어그룹','이재복','http://www.koreamediagroup.com/'],
 ['드림커뮤니케이션즈','조현일','http://www.dreamcom.co.kr/'],
 ['라이징팝스','김근식','http://www.risingpops.com/'],
 ['레인보우커뮤니케이션','유영석','http://www.rainbowpr.co.kr/'],
 ['로이스커뮤니케이션','황재규','http://www.roys.co.kr/'],
 ['㈜리앤컴','이준경','http://leencomm.co.kr/_html/'],
 ['㈜메타커뮤니케이션즈','한재방','http://www.metacomm.co.kr/'],
 ['미디컴','이재국','https://www.medicompr.co.kr/'],
 ['㈜브라이먼커뮤니케이션즈','박재수','http://www.briman.co.kr/'],
 ['브로더에이피(브로더파트너즈)','김성혜','https://www.brodeur.com/brodeur-ap/'],
 ['브라이트벨','박종현','http://brightbell.co.kr/'],
 ['스트래티지샐러드㈜','정용민','http://www.strategysalad.com/'],
 ['㈜시너지힐앤놀튼','정현순','http://hkblog.co.kr/'],
 ['써니피알','김완선','http://sunnypr.kr/'],
 ['㈜INR','이갑수','http://inrcomm.com/'],
 ['앨리슨+파트너스코리아','정민아/김태연/윤용로','https://allisonpr.co.kr/'],
 ['에그피알주식회사','홍순언','http://blog.ampr.co.kr/'],
 ['에델만코리아','장성빈','https://www.edelman.kr/'],
 ['㈜에이엠피알(amPR)','김희연','http://blog.ampr.co.kr/'],
 ['엑세스커뮤니케이션앤드컨설팅','이승세','http://www.ubrain.kr/'],
 ['NPR(엔피알인터커뮤니케이션)','윤영준','https://www.nprcom.co.kr/'],
 ['엔자임헬스㈜','김동석','http://www.enzaim.co.kr/'],
 ['㈜유브레인커뮤니케이션즈','이성용','http://www.ubrain.kr/'],
 ['㈜유앤아이컴','유정화','http://unicomm.co.kr/'],
 ['웨버샌드윅코리아','이중대','http://webershandwick.co.kr/'],
 ['웰컴어소씨에이츠','양승덕','http://www.wellcompr.com/'],
 ['이벤티노','박경덕','https://blog.naver.com/eventino'],
 ['이지스커뮤니케이션즈','전상훈/서교','http://www.egispr.co.kr/'],
 ['잇플루언서','이장원','https://www.itfluencer.co.kr/'],
 ['제이필름커뮤니케이션','이정우','https://jfilm.modoo.at/'],
 ['지오코리아','최보순','http://www.geocm.com/'],
 ['카멜월드와이드','김상욱','https://camelww.com/'],
 ['커뮤니케이션웨이브','정은경','http://www.commwave.co.kr/'],
 ['커뮤니케이션웍스','이승희','http://www.ccworks.co.kr/'],
 ['커뮤니케이션신화','유홍삭','http://www.prbank.co.kr/html/main/index.htm'],
 ['커뮤니케이션즈코리아','김경해','http://www.commkorea.com/'],
 ['커뮤니케이션즈온','곽도연','http://www.comm-on.co.kr/'],
 ['커뮤니크㈜','신명','http://www.communique.co.kr/'],
 ['㈜케이피알(KPR)','김주호','http://www.kpr.co.kr/'],
 ['코콤포터노벨리㈜','김기훈','https://www.korcom.com/www/html/index.php'],
 ['코핸즈','이선미','http://www.cohands.com/'],
 ['콜랩코리아㈜','김덕봉','http://www.collabkorea.com/'],
 ['㈜트레이','김정호','http://www.trey.co.kr/'],
 ['㈜프래드컴','문형진','http://www.pradcomm.co.kr/'],
 ['㈜프레인글로벌','김동욱/여준영','http://www.prain.com/v2/pages/'],
 ['프리스트커뮤니케이션즈','홍양선','http://www.prist.co.kr/'],
 ['플레시먼힐러드코리아','박영숙','https://fleishmanhillard.co.kr/'],
 ['플랜얼라이언스','문경호','http://planall.co.kr/'],
 ['피알 뉴스와이어(PR Newswire)','민재기','https://kr.prnasia.com/'],
 ['㈜피알와이드','이재철','http://www.prwide.com/'],
 ['㈜피알런','이회석','http://www.prrun.co.kr/'],
 ['피알봄','전은정','https://www.prbom.com/'],
 ['㈜피알원','조재형/이백수','http://www.prone.co.kr/'],
 ['호프만에이전시코리아','권기정','https://www.hoffman.com/'],
 ['해리','여혁종','http://harrie.co.kr/'],
 ['함샤우트 글로벌 & 딜라이트','김재희','http://www.hahmshout.com/'],
 ['함파트너스','함시원','http://www.hahmshout.com/']
];
/* 외국계·글로벌 네트워크 대행사 */
window.PR_GLOBAL={'에델만코리아':1,'웨버샌드윅코리아':1,'플레시먼힐러드코리아':1,'호프만에이전시코리아':1,'앨리슨+파트너스코리아':1,'브로더에이피(브로더파트너즈)':1,'코콤포터노벨리㈜':1,'㈜시너지힐앤놀튼':1,'피알 뉴스와이어(PR Newswire)':1};
